[versions]
kotest = "4.2.6"

[libraries]
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-assertions-core-jvm = { module = "io.kotest:kotest-assertions-core-jvm", version.ref = "kotest" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }

[bundles]
kotest = [ "kotest-assertions-core", "kotest-assertions-core-jvm", "kotest-runner-junit5" ]

[plugins]
detekt = "io.gitlab.arturbosch.detekt:1.23.4"
gitSemVer = "org.danilopianini.git-sensitive-semantic-versioning:2.0.1"
plugin-publish = "com.gradle.plugin-publish:1.2.1"
publish-on-central = "org.danilopianini.publish-on-central:5.0.19"
tasktree = "com.dorongold.task-tree:2.1.1"
