name: "A hopefully working pipeline"
on:
  - push
  - pull_request
  - workflow_dispatch

defaults:
  run:
    shell: bash

jobs:
  print-something:
    outputs:
      dice-result: ${{ steps.dice_step.outputs.dice }}
      java-versions: ${{ steps.java-versions.outputs.range }}
    env:
      JOB_VAR: "job-var"
    runs-on: ubuntu-22.04
    steps:
      - run: echo "I am back with a $JOB_VAR $STEP_VAR"
        name: This is a print
        shell: bash
        if: runner.os != 'Linux'
        env:
          STEP_VAR: "step-var"
      - name: Checkout the repo
        uses: actions/checkout@v4.1.1
      - name: generate a random number
        id: dice_step
        run: |
          ruby -e 'puts "dice=#{rand(1..6)}"' >> "$GITHUB_OUTPUT"
          echo ciao
      - name: print the random computed before
        run: |
          echo "I rolled a ${{ steps.dice_step.outputs.dice }}"
      - name: print the java versions
        id: java-versions
        run: ruby -e 'puts "range=#{[8, 11] + (16..rand(17..21)).to_a}"' >> "$GITHUB_OUTPUT"
  build:
    needs:
      - print-something
    strategy:
        fail-fast: false
        matrix:
          os: [ windows, macos, ubuntu ]
          java: ${{ fromJson(needs.print-something.outputs.java-versions) }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-build-${{ matrix.os }}-${{ matrix.java }}
      cancel-in-progress: true
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: print the dice result
        run: echo "${{ needs.print-something.outputs.dice-result }}"
      - name: configure java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: print java version
        run: java -version
      - name: Checkout the repo
        uses: actions/checkout@v4.1.1
      - run: true # ./gradlew assemble
  dry-deployment:
    needs:
      - build
    runs-on: ubuntu-22.04
    steps:
      - name: configure java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 8
      - name: Checkout the repo
        uses: actions/checkout@v4.1.1
        if: >
          !github.event.repository.fork
          && (
            github.event_name != 'pull_request'
            || github.event.pull_request.head.repo.full_name == github.repository
          )
        with:
          fetch-depth: 0
          fetch-tags: true
      - run: ./gradlew -PsigningKey=${{ secrets.SIGNING_KEY }} -PsigningPassword=${{ secrets.SIGNING_PASSWORD }} publishKotlinOSSRHPublicationToMCR publishPluginMavenPublicationToMavenCentralRepository close drop
        env:
          MAVEN_CENTRAL_USERNAME: danysk
          MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
